image: node:14.17.4

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test

Test:
  stage: test
  tags: -node
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn workspace server test
