version: "3.8"

services:
  server:
    container_name: app
    restart: always
    build: ./
    ports:
      - "4000:4000"
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mymongodb
    image: mongo
    ports:
      - "27017:27017"
